apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-git-backup
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-git-backup
rules:
# Core resources
- apiGroups: [""]
  resources:
    - namespaces
    - services
    - configmaps
    - secrets
    - persistentvolumes
    - persistentvolumeclaims
    - serviceaccounts
    - endpoints
  verbs: ["get", "list"]

# Apps resources
- apiGroups: ["apps"]
  resources:
    - deployments
    - daemonsets
    - statefulsets
    - replicasets
  verbs: ["get", "list"]

# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - roles
    - rolebindings
    - clusterroles
    - clusterrolebindings
  verbs: ["get", "list"]

# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
    - networkpolicies
  verbs: ["get", "list"]

# Storage resources
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
  verbs: ["get", "list"]

# Extensions (for older clusters)
- apiGroups: ["extensions"]
  resources:
    - ingresses
    - deployments
    - daemonsets
  verbs: ["get", "list"]

# Custom resources (if needed)
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs: ["get", "list"]

# Metrics and monitoring (optional)
- apiGroups: ["metrics.k8s.io"]
  resources:
    - nodes
    - pods
  verbs: ["get", "list"]

# Autoscaling
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs: ["get", "list"]

# Batch resources
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list"]

# Policy resources
- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-git-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-git-backup
subjects:
- kind: ServiceAccount
  name: kube-git-backup
  namespace: kube-system
